// this file uses/require vscode extension: REST Client

POST http://localhost:3333/api/links
Content-Type: application/json

{
  "code": "test",
  "url": "http://test.com"
}

###
GET http://localhost:3333/api/links

###
POST http://localhost:3333/test
Content-Type: application/json

{
  "code": "test"
}
